### ISSUE TITLE
the code seems incomplete.Could you share the complete coda?

### ISSUE THREAD

**Issue by weiwandege77** [nadeemlab/SeqX2Y#1]
thx for your paper and  code. @nadeemlab
Recently, I'm going to do some work about respiratory motion estimation
i noticed that the code file you shared is incomplete.
train.py and loss function file is missing
Could you share the complete code?

**Comment by sanadeem** [comment]
Thank you for your interest. All the code is in the models folder. It can be used for training as well. Unfortunately we are not maintaining this repo right now but will loop back with my team to add the training modules as well in the future.
